steps:
  - label: "build-gnu-x86-mmap"
    commands:
     - cargo build --release --features=backend-mmap
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          image: "rustvmm/dev:v5"
          always-pull: true

  - label: "build-musl-x86-mmap"
    commands:
     - cargo build --release --features=backend-mmap --target x86_64-unknown-linux-musl
    retry:
      automatic: false
    agents:
      platform: x86_64.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          image: "rustvmm/dev:v5"
          always-pull: true

  - label: "build-gnu-arm-mmap"
    commands:
     - cargo build --release --features=backend-mmap
    retry:
      automatic: false
    agents:
      platform: arm.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          image: "rustvmm/dev:v5"
          always-pull: true

  - label: "build-musl-arm-mmap"
    commands:
     - cargo build --release --features=backend-mmap --target aarch64-unknown-linux-musl
    retry:
      automatic: false
    agents:
      platform: arm.metal
      os: linux
    plugins:
      - docker#v3.0.1:
          image: "rustvmm/dev:v5"
          always-pull: true
